---
Mappings: 
  RegionMap: 
    us-east-1: 
      "64": "ami-a4dc46db"
    us-east-2: 
      "64": "ami-6a003c0f"
    us-west-1:
      "64": "ami-8d948ced"
    us-west-2:
      "64": "ami-db710fa3"
    ca-central-1:
      "64": "ami-7e21a11a"
    eu-west-1:
      "64": "ami-58d7e821"
    eu-west-2:
      "64": "ami-5daa463a"
    eu-west-3:
      "64": "ami-1960d164"
    eu-central-1:
      "64": "ami-c7e0c82c"
    ap-northeast-1:
      "64": "ami-48a45937"
    ap-northeast-2:
      "64": "ami-f030989e"
    ap-southeast-1:
      "64": "ami-81cefcfd"
    ap-southeast-2:
      "64": "ami-963cecf4"
    ap-south-1:
      "64": "ami-41e9c52e"
    sa-east-1:
      "64": "ami-67fca30b"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: vpc_ex005

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
        - Key: Name
          Value: ig_ex005

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  
  SubnetPublic:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/23
      Tags:
        - Key: Name
          Value: sub_pub_ex005
      VpcId: !Ref VPC
  
  SubnetPrivate:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/23
      Tags:
        - Key: Name
          Value: sub_pri_ex005
      VpcId: !Ref VPC

  NatGateway:
    Type: "AWS::EC2::NatGateway"
    Properties: 
      AllocationId: !GetAtt FloatingIpAddressNatGateway.AllocationId        
      SubnetId: !Ref SubnetPublic
    DependsOn: DefaultRoutePublic

  Ec2Endpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties: 
      VpcId: !Ref VPC
      ServiceName: com.amazonaws.us-east-1.ec2
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds: 
        - !Ref SubnetPrivate
      SecurityGroupIds: 
        - !Ref SecurityGroupEndpoint

  RouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: rtb_pub_ex005
  
  RouteTablePrivate:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: rtb_pri_ex005

  DefaultRoutePublic:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTablePublic
  
  DefaultRoutePrivate:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
      RouteTableId: !Ref RouteTablePrivate

  AssociateSubnetRouteTablePublic:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref SubnetPublic

  AssociateSubnetRouteTablePrivate:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref RouteTablePrivate
      SubnetId: !Ref SubnetPrivate
  
  FloatingIpAddressInstance:
    Type: "AWS::EC2::EIP"
    Properties:
      InstanceId: !Ref PublicInstance
      Domain: vpc

  FloatingIpAddressNatGateway:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  SecurityGroupInstances:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: sg_instances_ex005
      GroupDescription: "Security Group for Instances in ex-005"
      SecurityGroupIngress:
        - 
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - 
          CidrIp: 0.0.0.0/0
          IpProtocol: icmp
          FromPort: -1
          ToPort: -1
      VpcId: !Ref VPC

  SecurityGroupEndpoint:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: sg_endpoint_ex005
      GroupDescription: "Security Group for EC2 Endpoint in ex-005"
      SecurityGroupIngress:
        - 
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - 
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
      VpcId: !Ref VPC

  PublicInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", 64]
      InstanceType: t2.micro
      KeyName: acpkey1
      SecurityGroupIds: 
        - !Ref SecurityGroupInstances
      SubnetId: !Ref SubnetPublic
      Tags: 
        - Key: Name
          Value: i_pub_ex005
      UserData: !Base64
        "Fn::Join":
          - "\n"
          -
            - "#!/bin/bash"
            - "sudo apt-get update"
            - "sudo apt-get dist-upgrade -y"
            - "sudo apt-get install python3-pip -y"
            - "pip3 install awscli"
    DependsOn: DefaultRoutePublic

  PrivateInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", 64]
      InstanceType: t2.micro
      KeyName: acpkey1
      SecurityGroupIds: 
        - !Ref SecurityGroupInstances
      SubnetId: !Ref SubnetPrivate
      Tags: 
        - Key: Name
          Value: i_pri_ex005
      UserData: !Base64
        "Fn::Join":
          - "\n"
          -
            - "#!/bin/bash"
            - "sudo apt-get update"
            - "sudo apt-get dist-upgrade -y"
            - "sudo apt-get install python3-pip -y"
            - "pip3 install awscli"
    DependsOn: NatGateway
...